# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.5"
  - "2.7"

addons:
  postgresql: "9.4"

services:
  - postgresql
  - redis-server

before_script:
  - psql -c 'create database recruit;' -U postgres

install:
  - pip install -r requirements/dev.txt

script:
  - coverage run manage.py test

after_success:
  - coveralls
